apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .Values.repoName }}
  namespace: "argocd" 
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: {{ .Values.repoName }}
  url: {{ .Values.url }}
  secretArn: {{ .Values.secretArn }}

