apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Release.Namespace | default "argocd" }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  name: {{ .Values.clusterName }}
  server: {{ .Values.serverARN  }}
  config: {{ .Values.config | default "{\"tlsClientConfig\":{\"insecure\":false}}" | quote }}
