apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              cluster-role: hub
      - git:
          repoURL: '{{ .metadata.annotations.platform_url }}'
          revision: HEAD
          directories:
          - path: cluster-config/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{ .metadata.annotations.platform_url }}'
        path: charts/argocd-cluster-secret
        targetRevision: HEAD
        helm:
          parameters:
          - name: clusterName
            value: '{{ .path.basename }}'
          valueFiles:
          - '../../cluster-config/values.yaml'
          - '../../cluster-config/{{ .path.basename }}/values.yaml'
      destination:
        server: '{{ .server }}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
